
package gui;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import logica.Archivos;
import logica.GuardarP;
import logica.TablaPersonal;
import logica.TablaProyectos;
import logica.TablasDashboard;
import logica.Validar;

/**
 *
 * @author Carlos
 */
public class Home extends javax.swing.JFrame {

   
    int mousex, mousey;
    GuardarP rellenocombo = new GuardarP();
    Archivos objetoarchivo = new Archivos();
    FileInputStream streamp = null;
    FileInputStream streamp2 = null;
    TablaPersonal mostrar = new TablaPersonal();
    TablasDashboard muestradashboard = new TablasDashboard();
    int filesize;
    int filesize2;
   String savepersona;
   String saveproyecto;
   String savefecha;
   String nusuario;
   String inname;
   String instatus;
   String concepto = null;
    public Home() {
        initComponents();
        ImageIcon icono = new ImageIcon(getClass().getResource("/fotos/images/Orsalogo.png")); // Reemplaza "/ruta/a/tu/logo.png" con la ruta real de tu logo
        setIconImage(icono.getImage());
        
        rellenocombo.rellenocombos(gproyecto);
        rellenocombo.rellenocombos(fproyecto); 
        rellenocombo.rellenoresponsables(fresponsable);
        rellenocombo.rellenoresponsables(responsable);
        muestradashboard.tablageneral(tablap);
        muestradashboard.tablaherramienta(tablah);
        muestradashboard.tablavehiculo(tablav);
        //tabla
        
        savepersona = ffolio.getText(); 
        saveproyecto = (String) fproyecto.getSelectedItem();
        Date selectedDate = ffecha.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if(selectedDate != null){
            savefecha = dateFormat.format(selectedDate);
        } else {
             savefecha = "";
         }
        inname = fresponsable.getSelectedItem().toString();
        instatus = festatus.getSelectedItem().toString();
        
        //mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto,inname,instatus);
        mostrar.vistatabla(tablapersonal);
        
        nusuario = jlabeluser.getText();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabeluser = new javax.swing.JLabel();
        Personal = new javax.swing.JButton();
        proyectos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelfeed = new javax.swing.JLabel();
        tabbedpanel = new javax.swing.JTabbedPane();
        panelinicio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablapersonal = new javax.swing.JTable();
        gproyecto = new javax.swing.JComboBox<>();
        gcosto = new javax.swing.JTextField();
        choosergfecha = new com.toedter.calendar.JDateChooser();
        fproyecto = new javax.swing.JComboBox<>();
        gfactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gdesc = new javax.swing.JTextArea();
        ffecha = new com.toedter.calendar.JDateChooser();
        savep = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombrefactura = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        glimpia = new javax.swing.JButton();
        limpiafiltros = new javax.swing.JLabel();
        ffolio = new javax.swing.JTextField();
        gfolio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        responsable = new javax.swing.JComboBox<>();
        modificar = new javax.swing.JButton();
        fresponsable = new javax.swing.JComboBox<>();
        idset = new javax.swing.JLabel();
        festatus = new javax.swing.JComboBox<>();
        gestatus = new javax.swing.JComboBox<>();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        gconcepto = new javax.swing.JTextField();
        helpconcepto = new javax.swing.JLabel();
        fconcepto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablap = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablav = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablah = new javax.swing.JTable();
        botonherramienta = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        botonproyectos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homepanel.setBackground(new java.awt.Color(255, 255, 255));
        homepanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/Orsalogo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/Sample_User_Icon (1).png"))); // NOI18N

        jlabeluser.setFont(new java.awt.Font("Yu Gothic Medium", 3, 12)); // NOI18N
        jlabeluser.setText(" ");

        Personal.setBackground(new java.awt.Color(102, 102, 102));
        Personal.setText("Personal");
        Personal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Personal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Personal.setFocusable(false);
        Personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PersonalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PersonalMouseReleased(evt);
            }
        });
        Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalActionPerformed(evt);
            }
        });

        proyectos.setBackground(new java.awt.Color(102, 102, 102));
        proyectos.setText("Proyectos");
        proyectos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        proyectos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proyectos.setFocusPainted(false);
        proyectos.setFocusable(false);
        proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                proyectosMousePressed(evt);
            }
        });
        proyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyectosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabeluser, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlabeluser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(Personal)
                .addGap(65, 65, 65)
                .addComponent(proyectos)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        homepanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 520));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelfeed.setBackground(new java.awt.Color(0, 0, 0));
        labelfeed.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelfeed.setForeground(new java.awt.Color(255, 255, 255));
        labelfeed.setText("Inicio");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(labelfeed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 583, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelfeed)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        homepanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 50));

        tabbedpanel.setBackground(new java.awt.Color(255, 255, 255));
        tabbedpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabbedpanelMousePressed(evt);
            }
        });

        panelinicio.setBackground(new java.awt.Color(255, 255, 255));
        panelinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelinicioMouseEntered(evt);
            }
        });
        panelinicio.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/rayo (1).png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        panelinicio.add(jLabel5);
        jLabel5.setBounds(420, 100, 190, 220);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/persona (2).png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        panelinicio.add(jLabel3);
        jLabel3.setBounds(140, 70, 200, 270);

        tabbedpanel.addTab("Inicio", panelinicio);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setToolTipText("");

        tablapersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Personal", "Proyecto", "Costo", "Fecha", "Descripción", "Factura", "Autorización"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablapersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablapersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapersonalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablapersonalMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablapersonal);
        if (tablapersonal.getColumnModel().getColumnCount() > 0) {
            tablapersonal.getColumnModel().getColumn(0).setResizable(false);
            tablapersonal.getColumnModel().getColumn(1).setResizable(false);
            tablapersonal.getColumnModel().getColumn(2).setResizable(false);
            tablapersonal.getColumnModel().getColumn(3).setResizable(false);
            tablapersonal.getColumnModel().getColumn(4).setResizable(false);
            tablapersonal.getColumnModel().getColumn(5).setResizable(false);
            tablapersonal.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 560, 380));

        gproyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto", "Oficina", "Personales", "Varios" }));
        gproyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gproyectoActionPerformed(evt);
            }
        });
        jPanel4.add(gproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 123, 147, -1));
        jPanel4.add(gcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 231, 98, -1));
        jPanel4.add(choosergfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 67, 149, -1));

        fproyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto" }));
        fproyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fproyectoMousePressed(evt);
            }
        });
        fproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fproyectoActionPerformed(evt);
            }
        });
        jPanel4.add(fproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, -1));

        gfactura.setText("Factura");
        gfactura.setToolTipText("");
        gfactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gfacturaMousePressed(evt);
            }
        });
        jPanel4.add(gfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 281, 78, -1));

        gdesc.setColumns(20);
        gdesc.setRows(5);
        jScrollPane2.setViewportView(gdesc);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 126, 57));

        ffecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ffechaMousePressed(evt);
            }
        });
        jPanel4.add(ffecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        savep.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        savep.setText("Guardar");
        savep.setToolTipText("");
        savep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                savepMousePressed(evt);
            }
        });
        jPanel4.add(savep, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 373, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/icone-de-filtre-noir (1).png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Actividades");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 41, -1, -1));

        jLabel8.setText("MXN");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 234, -1, -1));

        jLabel9.setText("$");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 234, -1, -1));

        nombrefactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nombrefactura.setText("sinarchivo.pdf");
        jPanel4.add(nombrefactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 259, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/botecito (1).png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 281, 36, -1));

        glimpia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        glimpia.setText("Limpia");
        glimpia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        glimpia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                glimpiaMousePressed(evt);
            }
        });
        glimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glimpiaActionPerformed(evt);
            }
        });
        jPanel4.add(glimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 65, -1));

        limpiafiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/botecito (1).png"))); // NOI18N
        limpiafiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiafiltros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiafiltrosMousePressed(evt);
            }
        });
        jPanel4.add(limpiafiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        ffolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffolioActionPerformed(evt);
            }
        });
        jPanel4.add(ffolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, -1));
        jPanel4.add(gfolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 95, 53, -1));

        jLabel6.setText("Folio:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel11.setText("Folio:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 98, -1, -1));

        responsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Responsable" }));
        responsable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsableActionPerformed(evt);
            }
        });
        jPanel4.add(responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 157, 147, -1));

        modificar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        modificar.setText("Modifica");
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarMousePressed(evt);
            }
        });
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel4.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        fresponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Responsable" }));
        fresponsable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fresponsable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fresponsableMousePressed(evt);
            }
        });
        fresponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fresponsableActionPerformed(evt);
            }
        });
        jPanel4.add(fresponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, -1));
        jPanel4.add(idset, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 24, 20));

        festatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus", "Cerrado", "Pendiente" }));
        festatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        festatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                festatusMousePressed(evt);
            }
        });
        festatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                festatusActionPerformed(evt);
            }
        });
        jPanel4.add(festatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 77, -1));

        gestatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus", "Cerrado", "Pendiente" }));
        gestatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestatusActionPerformed(evt);
            }
        });
        jPanel4.add(gestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 197, 147, -1));

        actualizar.setBackground(new java.awt.Color(51, 51, 255));
        actualizar.setText("A");
        actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizar.setFocusPainted(false);
        actualizar.setFocusable(false);
        actualizar.setRequestFocusEnabled(false);
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actualizarMousePressed(evt);
            }
        });
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel4.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 27, -1));

        eliminar.setBackground(new java.awt.Color(255, 0, 0));
        eliminar.setText("E");
        eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setFocusPainted(false);
        eliminar.setFocusable(false);
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarMousePressed(evt);
            }
        });
        jPanel4.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 27, -1));

        jLabel12.setText("Concepto:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 98, -1, -1));
        jPanel4.add(gconcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 95, 24, -1));

        helpconcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/Black_question_mark (1).png"))); // NOI18N
        helpconcepto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpconcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpconceptoMousePressed(evt);
            }
        });
        jPanel4.add(helpconcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 67, 24, -1));

        fconcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fconceptoActionPerformed(evt);
            }
        });
        jPanel4.add(fconcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 10, 30, -1));

        jLabel13.setText("Concepto:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        tabbedpanel.addTab("Personal", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });

        tablap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Proyecto", "Gastos", "Contrato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(tablap);
        if (tablap.getColumnModel().getColumnCount() > 0) {
            tablap.getColumnModel().getColumn(0).setResizable(false);
            tablap.getColumnModel().getColumn(1).setResizable(false);
            tablap.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel14.setText("Seguimiento de herramienta");

        jLabel15.setText("Seguimiento de vehículos");

        tablav.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vehículo", "Personal", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablav);
        if (tablav.getColumnModel().getColumnCount() > 0) {
            tablav.getColumnModel().getColumn(0).setResizable(false);
            tablav.getColumnModel().getColumn(1).setResizable(false);
            tablav.getColumnModel().getColumn(2).setResizable(false);
        }

        tablah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Herramienta", "Personal", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablah.setEnabled(false);
        jScrollPane5.setViewportView(tablah);
        if (tablah.getColumnModel().getColumnCount() > 0) {
            tablah.getColumnModel().getColumn(0).setResizable(false);
            tablah.getColumnModel().getColumn(1).setResizable(false);
            tablah.getColumnModel().getColumn(2).setResizable(false);
        }

        botonherramienta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/tool (1).png"))); // NOI18N
        botonherramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonherramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonherramientaMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/addcaricon (1).png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });

        jLabel18.setText("Seguimiento de proyectos");

        botonproyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/rayito (1).png"))); // NOI18N
        botonproyectos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonproyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonproyectosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonproyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonproyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(299, 299, 299)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE)
        );

        tabbedpanel.addTab("Proyectos", jPanel1);

        homepanel.add(tabbedpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 760, 470));

        getContentPane().add(homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex,y - mousey);
        
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        mousex = evt.getX();
        mousey = evt.getY();

    }//GEN-LAST:event_jPanel3MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MousePressed

    private void PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalActionPerformed

    private void proyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proyectosActionPerformed

    private void PersonalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalMouseReleased

    private void PersonalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalMousePressed
        // TODO add your handling code here:
        labelfeed.setText("Personal");
        tabbedpanel.setSelectedIndex(1);
    }//GEN-LAST:event_PersonalMousePressed

    private void proyectosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proyectosMousePressed
        // TODO add your handling code here:
        labelfeed.setText("Proyectos");
        tabbedpanel.setSelectedIndex(2);
    }//GEN-LAST:event_proyectosMousePressed

    private void tabbedpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbedpanelMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tabbedpanelMousePressed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        labelfeed.setText("Proyectos");
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        //muestradashboard.tablageneral(tablap);
        muestradashboard.tablaherramienta(tablah);
        muestradashboard.tablavehiculo(tablav);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void botonproyectosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonproyectosMousePressed
        // TODO add your handling code here:
        MenuProyecto screen = new MenuProyecto();
        screen.setVisible(true);
        screen.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonproyectosMousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        // TODO add your handling code here:
        MenuVehiculo pantalla = new MenuVehiculo();

        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);//poner la pantalla en medio
        muestradashboard.tablaherramienta(tablah);
    }//GEN-LAST:event_jLabel17MousePressed

    private void botonherramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonherramientaMousePressed
        // TODO add your handling code here:
        MenuHerramienta pantalla = new MenuHerramienta();

        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);//poner la pantalla en medio
    }//GEN-LAST:event_botonherramientaMousePressed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        labelfeed.setText("Personal");
        //mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto);

    }//GEN-LAST:event_jPanel4MouseEntered

    private void limpiafiltrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiafiltrosMousePressed
        // TODO add your handling code here:
        ffolio.setText("");
        fproyecto.setSelectedIndex(0);
        fresponsable.setSelectedIndex(0);
        ffecha.setDate(null);
        festatus.setSelectedIndex(0);
        mostrar.vistatabla(tablapersonal);
    }//GEN-LAST:event_limpiafiltrosMousePressed

    private void glimpiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glimpiaMousePressed
        gfolio.setText("");
        gproyecto.setSelectedIndex(0);
        choosergfecha.setDate(null);
        gdesc.setText("");
        gcosto.setText("");
        responsable.setSelectedIndex(0);
        gestatus.setSelectedIndex(0);
        streamp = null;
        streamp2 = null;
      // mostrar.vistatabla(tablapersonal);
    }//GEN-LAST:event_glimpiaMousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        streamp = null;
        streamp2 = null;
        nombrefactura.setText("sinarchivo.pdf");
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:

        savepersona = ffolio.getText();
        saveproyecto = (String) fproyecto.getSelectedItem();
        Date selectedDate = ffecha.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if(selectedDate != null){
            savefecha = dateFormat.format(selectedDate);
        } else{
            savefecha = "";
        }
        inname = fresponsable.getSelectedItem().toString();
        instatus = festatus.getSelectedItem().toString();
        mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto,inname,instatus,fconcepto.getText());
    }//GEN-LAST:event_jLabel4MousePressed

    private void savepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savepMousePressed

        GuardarP guardar = new GuardarP();
        String boxpersona;
        String boxproyecto;
        String stringfecha;
        boxpersona = gfolio.getText();
        boxproyecto = (String) gproyecto.getSelectedItem();
        Date saveselectedDate = choosergfecha.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        stringfecha = dateFormat.format(saveselectedDate);

        String describe = gdesc.getText();
        String costo = gcosto.getText();
        nusuario = jlabeluser.getText();
        String nombreresponsable = responsable.getSelectedItem().toString();
        String estatus = gestatus.getSelectedItem().toString();
        concepto = gconcepto.getText();
        //El pdf factura se recupera desde el boton de factura
        
        if(boxpersona.equals("Persona") || boxproyecto.equals("Proyecto")){
            JOptionPane.showMessageDialog(null,"Llene todos los campos");
        }else{
            if(concepto.equals(null)){//insertar un set
            //Enviar a query
            guardar.saveactividad(nusuario, boxpersona, boxproyecto,stringfecha, costo, streamp, filesize, describe,nombreresponsable,estatus,gconcepto.getText());
            }else{
               guardar.saveactividad(nusuario, boxpersona, boxproyecto,stringfecha, costo, streamp, filesize, describe,nombreresponsable,estatus,concepto); 
               concepto = null;// se vuelve a inicializar la variable
            }
        }
        tablapersonal.repaint();
        tablapersonal.revalidate();
        //inname = fresponsable.getSelectedItem().toString();
        
        //mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto,inname,instatus);
        mostrar.vistatabla(tablapersonal);
        streamp = null;//Limpiar variable de archivo

        muestradashboard.tablageneral(tablap);//Para actualizar gastos

    }//GEN-LAST:event_savepMousePressed

    private void ffechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffechaMousePressed
        // TODO add your handling code here:
        //mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto);
    }//GEN-LAST:event_ffechaMousePressed

    private void gfacturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gfacturaMousePressed

        objetoarchivo.recuperapdf();
        try {
            streamp = objetoarchivo.streampdf();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        filesize = objetoarchivo.sizearchivo();

        nombrefactura.setText(objetoarchivo.regresanombre());

    }//GEN-LAST:event_gfacturaMousePressed

    private void fproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fproyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fproyectoActionPerformed

    private void fproyectoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fproyectoMousePressed
        // TODO add your handling code here:
       // mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto);
    }//GEN-LAST:event_fproyectoMousePressed

    private void gproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gproyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gproyectoActionPerformed

    private void panelinicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelinicioMouseEntered
        // TODO add your handling code here:
        labelfeed.setText("Inicio");
    }//GEN-LAST:event_panelinicioMouseEntered

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        labelfeed.setText("Proyectos");
        tabbedpanel.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        labelfeed.setText("Personal");
        tabbedpanel.setSelectedIndex(1);

    }//GEN-LAST:event_jLabel3MousePressed

    private void tablapersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapersonalMouseClicked
        // TODO add your handling code here:
        //mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto);
         try {
            // TODO add your handling code here:
            streamp2 = mostrar.setfactura();
            
            mostrar.pintaactividad(tablapersonal, idset, choosergfecha, gfolio, gproyecto, responsable, gcosto, gdesc,responsable,gestatus,gconcepto);
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         int filaSeleccionada = tablapersonal.getSelectedRow();
    int columnaContrato = getColumnaPorNombre("Factura"); // Ajusta este valor al índice real de la columna "contrato"
    
    if (filaSeleccionada != -1) { // Verificar si se ha seleccionado alguna fila
        Object valorCelda = tablapersonal.getValueAt(filaSeleccionada, columnaContrato);
        if (valorCelda != null && !valorCelda.toString().isEmpty()) { // Verificar si el valor de la celda no es nulo ni vacío
            nombrefactura.setText("ArchivoCargado.pdf");
        } else {
            nombrefactura.setText("sinarchivo.pdf");
        }
    }
    }//GEN-LAST:event_tablapersonalMouseClicked

    //Método para extraer string de la columna del archivo
    private int getColumnaPorNombre(String nombreColumna) {
    for (int i = 0; i < tablapersonal.getColumnCount(); i++) {
        if (tablapersonal.getColumnName(i).equals(nombreColumna)) {
            return i;
        }
    }
    return -1; // Retorna -1 si no se encuentra la columna
}
    private void ffolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffolioActionPerformed

    private void responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsableActionPerformed

    private void modificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMousePressed
        // TODO add your handling code here:
        //insertar función de update
        if(streamp != null){
        rellenocombo.updateactividad(idset,choosergfecha,gfolio,gproyecto,responsable,gcosto,streamp,filesize,gdesc,jlabeluser,gestatus,gconcepto);
        }else{
            try {
                 if(streamp2 != null){
                filesize2 = streamp2.available();
                
                }
                 rellenocombo.updateactividad(idset,choosergfecha,gfolio,gproyecto,responsable,gcosto,streamp2,filesize2,gdesc,jlabeluser,gestatus,gconcepto);
               
                
                
                
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
        }
       //mostrar.mostrartabla(tablapersonal, savefecha, savepersona, saveproyecto,inname,instatus);
       mostrar.vistatabla(tablapersonal);
       streamp2=null;
       streamp=null;
        
    }//GEN-LAST:event_modificarMousePressed

    private void fresponsableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fresponsableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fresponsableMousePressed

    private void fresponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fresponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fresponsableActionPerformed

    private void tablapersonalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapersonalMousePressed
       
       
        
      
       
        
    }//GEN-LAST:event_tablapersonalMousePressed

    private void glimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glimpiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_glimpiaActionPerformed

    private void festatusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_festatusMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_festatusMousePressed

    private void festatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_festatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_festatusActionPerformed

    private void gestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestatusActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarActionPerformed

    private void actualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMousePressed
        // TODO add your handling code here:
        gproyecto.removeAllItems();
        rellenocombo.rellenocombos(gproyecto);
        fproyecto.removeAllItems();
        rellenocombo.rellenocombos(fproyecto); 
        fresponsable.removeAllItems();
        rellenocombo.rellenoresponsables(fresponsable);
        responsable.removeAllItems();
        rellenocombo.rellenoresponsables(responsable);
        
        muestradashboard.tablageneral(tablap);
        muestradashboard.tablaherramienta(tablah);
        muestradashboard.tablavehiculo(tablav);
        mostrar.vistatabla(tablapersonal);
        
    }//GEN-LAST:event_actualizarMousePressed

    private void eliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMousePressed
        // TODO add your handling code here:
        rellenocombo.elminaractividad(idset.getText());
        mostrar.vistatabla(tablapersonal);
    }//GEN-LAST:event_eliminarMousePressed

    private void fconceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fconceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fconceptoActionPerformed

    private void helpconceptoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpconceptoMousePressed
        // TODO add your handling code here:
        MenuConcepto pantallaconcepto = new MenuConcepto();
        pantallaconcepto.setVisible(true);
        pantallaconcepto.setLocationRelativeTo(null);
    }//GEN-LAST:event_helpconceptoMousePressed

    
    
    public void refreshherramienta(){
          muestradashboard.tablaherramienta(tablah);
    }
 
 public void settextjlabeluser(String texto){
     jlabeluser.setText(texto);
      
        if(texto.equals("adminingenieria") || texto.equals("JesusOrtega") || texto.equals("GustavoOrtega") ){
            gestatus.addItem("Firmado");
        }
 }
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Personal;
    private javax.swing.JButton actualizar;
    private javax.swing.JLabel botonherramienta;
    private javax.swing.JLabel botonproyectos;
    private com.toedter.calendar.JDateChooser choosergfecha;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fconcepto;
    private javax.swing.JComboBox<String> festatus;
    private com.toedter.calendar.JDateChooser ffecha;
    private javax.swing.JTextField ffolio;
    private javax.swing.JComboBox<String> fproyecto;
    private javax.swing.JComboBox<String> fresponsable;
    private javax.swing.JTextField gconcepto;
    private javax.swing.JTextField gcosto;
    private javax.swing.JTextArea gdesc;
    private javax.swing.JComboBox<String> gestatus;
    private javax.swing.JButton gfactura;
    private javax.swing.JTextField gfolio;
    private javax.swing.JButton glimpia;
    private javax.swing.JComboBox<String> gproyecto;
    private javax.swing.JLabel helpconcepto;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel idset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jlabeluser;
    private javax.swing.JLabel labelfeed;
    private javax.swing.JLabel limpiafiltros;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel nombrefactura;
    private javax.swing.JPanel panelinicio;
    private javax.swing.JButton proyectos;
    private javax.swing.JComboBox<String> responsable;
    private javax.swing.JButton savep;
    private javax.swing.JTabbedPane tabbedpanel;
    private javax.swing.JTable tablah;
    private javax.swing.JTable tablap;
    public javax.swing.JTable tablapersonal;
    private javax.swing.JTable tablav;
    // End of variables declaration//GEN-END:variables
}
