/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.itextpdf.text.log.Logger;
import com.toedter.calendar.JDateChooser;
import java.awt.List;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import logica.Archivos;
import logica.TablasProyecto;
 
/**
 *
 * @author Carlos
 */
public class MenuProyecto extends javax.swing.JFrame {

    /**
     * Creates new form MenuProyecto
     */
    int mousex;
    int mousey;
    FileInputStream streamp;
    int filesize;
    
    FileInputStream streamp2;
    int filesize2;
    Archivos objetoarchivo = new Archivos();
    TablasProyecto tabla = new TablasProyecto();
    public MenuProyecto() {
        initComponents();
       
      tabla.rellenoproyectos(buscaproyecto);
      tabla.rellenoproyectos(insertaproyecto);
      tabla.rellenoproyectoa(proyectoa);
      tabla.muestratablamenup(tablahub);
      tabla.tablaasignados(tablaasignados);
      tabla.tablavistaasignaciones(tablaasignacion);
      nuevo.setSelected(false);
      modificar.setSelected(false);
      nombrep.setEnabled(false);
      pcotiza.setEnabled(false);
      deadline.setEnabled(false);
      gcontrato.setEnabled(false);
      borracontrato.setEnabled(false);
      idasignacion.setEnabled(false);
      insertaproyecto.setEnabled(false);
      textoactualizaciones.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablahub = new javax.swing.JTable();
        filtraproyecto = new javax.swing.JLabel();
        buscaproyecto = new javax.swing.JComboBox<>();
        limpiaproyecto = new javax.swing.JLabel();
        pcotiza = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombrecontrato = new javax.swing.JLabel();
        gcontrato = new javax.swing.JButton();
        borracontrato = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        modificar = new javax.swing.JCheckBox();
        nombrep = new javax.swing.JTextField();
        deadline = new com.toedter.calendar.JDateChooser();
        nuevo = new javax.swing.JCheckBox();
        guardap = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaasignacion = new javax.swing.JTable();
        limpiafiltro = new javax.swing.JLabel();
        updateproceso = new javax.swing.JComboBox<>();
        insertaproyecto = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoactualizaciones = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        proyectoa = new javax.swing.JComboBox<>();
        procesoa = new javax.swing.JComboBox<>();
        guarda = new javax.swing.JButton();
        filtra = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaasignados = new javax.swing.JTable();
        newcheck = new javax.swing.JCheckBox();
        idasignacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Proyectos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablahub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablahub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablahub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablahubMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablahubMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablahub);

        filtraproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/icone-de-filtre-noir (1).png"))); // NOI18N
        filtraproyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtraproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                filtraproyectoMousePressed(evt);
            }
        });

        buscaproyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto" }));
        buscaproyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscaproyectoMousePressed(evt);
            }
        });
        buscaproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaproyectoActionPerformed(evt);
            }
        });

        limpiaproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/botecito (1).png"))); // NOI18N
        limpiaproyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiaproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiaproyectoMousePressed(evt);
            }
        });

        jLabel9.setText("$");

        jLabel8.setText("MXN");

        nombrecontrato.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nombrecontrato.setText("sinarchivo.pdf");

        gcontrato.setText("Contrato");
        gcontrato.setToolTipText("");
        gcontrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gcontrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gcontratoMousePressed(evt);
            }
        });

        borracontrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/botecito (1).png"))); // NOI18N
        borracontrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borracontrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                borracontratoMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Insertar datos");

        modificar.setBackground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.setBorder(null);
        modificar.setContentAreaFilled(false);
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.setFocusPainted(false);
        modificar.setFocusable(false);
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarMousePressed(evt);
            }
        });

        nombrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrepActionPerformed(evt);
            }
        });

        nuevo.setText("Nuevo");
        nuevo.setBorder(null);
        nuevo.setContentAreaFilled(false);
        nuevo.setFocusPainted(false);
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevoMousePressed(evt);
            }
        });

        guardap.setText("Guardar");
        guardap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardapMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(filtraproyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiaproyecto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(modificar)
                                        .addGap(92, 92, 92)
                                        .addComponent(nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(nuevo)
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel1)))
                                .addGap(27, 27, 27))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(gcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(borracontrato))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(guardap, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pcotiza, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(nombrecontrato)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(filtraproyecto)
                            .addComponent(buscaproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limpiaproyecto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nuevo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificar)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcotiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(66, 66, 66)
                        .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(nombrecontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borracontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        jTabbedPane1.addTab("Hub", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tablaasignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaasignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaasignacionMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaasignacion);

        limpiafiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/botecito (1).png"))); // NOI18N
        limpiafiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiafiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiafiltroMousePressed(evt);
            }
        });

        updateproceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proceso", "Pendiente", "En curso", "Finalizado" }));

        insertaproyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto" }));
        insertaproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaproyectoActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(textoactualizaciones);

        jLabel3.setText("Personal asignado:");

        proyectoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto" }));
        proyectoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyectoaActionPerformed(evt);
            }
        });

        procesoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proceso", "Pendiente", "En curso ", "Finalizada" }));

        guarda.setText("Guardar");
        guarda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guarda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardaMousePressed(evt);
            }
        });

        filtra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/icone-de-filtre-noir (1).png"))); // NOI18N
        filtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                filtraMousePressed(evt);
            }
        });

        tablaasignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaasignados);

        newcheck.setText("Nuevo");
        newcheck.setContentAreaFilled(false);
        newcheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newcheck.setFocusPainted(false);
        newcheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newcheckMouseClicked(evt);
            }
        });
        newcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcheckActionPerformed(evt);
            }
        });

        jLabel4.setText("Asignaciones");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(filtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proyectoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(procesoa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiafiltro))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guarda)
                        .addGap(215, 215, 215))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(139, 139, 139)
                                .addComponent(newcheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(idasignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(insertaproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(updateproceso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(173, 173, 173))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(newcheck)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(idasignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateproceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(insertaproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guarda)
                        .addGap(86, 86, 86))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpiafiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtra)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(proyectoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(procesoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignaciones", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
       
        this.setLocation(x - mousex,y - mousey);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void filtraproyectoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtraproyectoMousePressed
        // TODO add your handling code here:
        String nombreproyecto = buscaproyecto.getSelectedItem().toString();
        if(nombreproyecto.equals("Proyecto")){
            tabla.tablamenup(tablahub);
        }else{
        tabla.filtroproyecto(tablahub,nombreproyecto);
        }
    }//GEN-LAST:event_filtraproyectoMousePressed

    private void buscaproyectoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaproyectoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaproyectoMousePressed

    private void buscaproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaproyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaproyectoActionPerformed

    private void limpiaproyectoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiaproyectoMousePressed
        // TODO add your handling code here:
        buscaproyecto.setSelectedIndex(0);
        tabla.tablamenup(tablahub);
       
    }//GEN-LAST:event_limpiaproyectoMousePressed

    private void gcontratoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gcontratoMousePressed
        if(gcontrato.isEnabled()){
        objetoarchivo.recuperapdf();
        try {
             streamp = objetoarchivo.streampdf();
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(MenuProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        filesize = objetoarchivo.sizearchivo();

        nombrecontrato.setText(objetoarchivo.regresanombre());
        }
    }//GEN-LAST:event_gcontratoMousePressed

    private void borracontratoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borracontratoMousePressed
        if(modificar.isSelected() || nuevo.isSelected()){
        streamp = null;
        filesize = 0;
        streamp2 = null;
        filesize2 = 0;
        nombrecontrato.setText("sinarchivo.pdf");
        }
    }//GEN-LAST:event_borracontratoMousePressed

    private void modificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMousePressed
        // TODO add your handling code here:
         if(modificar.isSelected()){
            nombrep.setEnabled(false);
            pcotiza.setEnabled(true);
            deadline.setEnabled(true);
            gcontrato.setEnabled(true);
            borracontrato.setEnabled(true);
            
            
            
        
        }
        
        if(!modificar.isSelected()){
            nombrep.setEnabled(false);
            pcotiza.setEnabled(false);
            deadline.setEnabled(false);
            gcontrato.setEnabled(false);
            borracontrato.setEnabled(false);
            
           
           
        }
        
    }//GEN-LAST:event_modificarMousePressed

    private void nombrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrepActionPerformed

    private void nuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMousePressed
       
        if(nuevo.isSelected()){
            nombrep.setEnabled(true);
            pcotiza.setEnabled(true);
            deadline.setEnabled(true);
            gcontrato.setEnabled(true);
            borracontrato.setEnabled(true);
            
            nombrep.setText("");
            pcotiza.setText("");
            deadline.setDate(null);
            nombrecontrato.setText("sinarchivo.pdf");
        
        }
        
        if(!nuevo.isSelected()){
            nombrep.setEnabled(false);
            pcotiza.setEnabled(false);
            deadline.setEnabled(false);
            gcontrato.setEnabled(false);
            borracontrato.setEnabled(false);
            
            nombrep.setText("");
            pcotiza.setText("");
            deadline.setDate(null);
            nombrecontrato.setText("sinarchivo.pdf");
        }
        
    }//GEN-LAST:event_nuevoMousePressed

    private void nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseClicked
        // TODO add your handling code here:}
       
        if(nuevo.isSelected()){
            modificar.setSelected(false);
            nombrep.setEnabled(true);
            pcotiza.setEnabled(true);
            deadline.setEnabled(true);
            gcontrato.setEnabled(true);
            borracontrato.setEnabled(true);
            
            nombrep.setText("");
            pcotiza.setText("");
            deadline.setDate(null);
            nombrecontrato.setText("sinarchivo.pdf");
        
        }
        
        if(!nuevo.isSelected()){
            nombrep.setEnabled(false);
            pcotiza.setEnabled(false);
            deadline.setEnabled(false);
            gcontrato.setEnabled(false);
            borracontrato.setEnabled(false);
            
            nombrep.setText("");
            pcotiza.setText("");
            deadline.setDate(null);
            nombrecontrato.setText("sinarchivo.pdf");
        }
    }//GEN-LAST:event_nuevoMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        // TODO add your handling code here:}
        if(modificar.isSelected()){
            nuevo.setSelected(false);
            nombrep.setEnabled(false);
            pcotiza.setEnabled(true);
            deadline.setEnabled(true);
            gcontrato.setEnabled(true);
            borracontrato.setEnabled(true);
            
            
            
        
        }
        
        if(!modificar.isSelected()){
            nombrep.setEnabled(false);
            pcotiza.setEnabled(false);
            deadline.setEnabled(false);
            gcontrato.setEnabled(false);
            borracontrato.setEnabled(false);
            
         
        }
        
    }//GEN-LAST:event_modificarMouseClicked

    private void guardapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardapMousePressed
        // TODO add your handling code here:
      
      String savefecha;
      Date selectedDate;
      SimpleDateFormat dateFormat;
      if(nuevo.isSelected()){
        selectedDate = deadline.getDate();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if(selectedDate != null){
            savefecha = dateFormat.format(selectedDate);
        } else {
             savefecha = null;
         }
        tabla.crearproyecto(nombrep, pcotiza, streamp, filesize, savefecha);
        //tabla.tablamenup(tablahub);
        tablahub.repaint();
        tablahub.revalidate();
        streamp = null;//Limpiar variable de archivo
        }
      if(modificar.isSelected()){
        selectedDate = deadline.getDate();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if(selectedDate != null){
            savefecha = dateFormat.format(selectedDate);
        } else {
             savefecha = null;
         } 
          if(streamp==null && streamp2!=null){
          streamp2 = tabla.setcontrato();
          try {
             filesize2 = tabla.setcontrato().available();
             tabla.updateproyecto(tablahub, nombrep, pcotiza,streamp2,filesize2, savefecha);
          } catch (IOException ex) {
              java.util.logging.Logger.getLogger(MenuProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        }else{
             tabla.updateproyecto(tablahub, nombrep, pcotiza,streamp,filesize, savefecha);//La opción cuando hay un nuevo archivo
          }
        
        //tabla.tablamenup(tablahub);
        tablahub.repaint();
        tablahub.revalidate();
      }
      
       nombrep.setText("");
       pcotiza.setText("");
       deadline.setDate(null);
       nombrecontrato.setText("sinarchivo.pdf");
      
       // Update the table content
        tabla.muestratablamenup(tablahub);

    // Repaint and revalidate to ensure the table is updated
        tablahub.repaint();
        tablahub.revalidate();
       
        
    }//GEN-LAST:event_guardapMousePressed

    private void tablahubMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablahubMousePressed
        
    }//GEN-LAST:event_tablahubMousePressed

    private void proyectoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyectoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proyectoaActionPerformed

    private void insertaproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaproyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaproyectoActionPerformed

    private void newcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newcheckActionPerformed

    private void newcheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcheckMouseClicked
        // TODO add your handling code here:
      idasignacion.setText("");
      updateproceso.setSelectedIndex(0);
      insertaproyecto.setSelectedIndex(0);
      textoactualizaciones.setText("");
      insertaproyecto.setEnabled(false);
      textoactualizaciones.setEnabled(false);
      //tabla.insertarpersonalasignado(tablaasignados, idasignacion.getText());
      tabla.tablaasignados(tablaasignados);
      
      if(newcheck.isSelected()){
        //idasignacion.setEnabled(true);
        insertaproyecto.setEnabled(true);
        textoactualizaciones.setEnabled(true);
      }
      
        if(!newcheck.isSelected()){
        //idasignacion.setEnabled(false);
        insertaproyecto.setEnabled(false);
        textoactualizaciones.setEnabled(false);
      }
        
    }//GEN-LAST:event_newcheckMouseClicked

    private void guardaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardaMousePressed
        // TODO add your handling code here:
        String status = updateproceso.getSelectedItem().toString();
        if(newcheck.isSelected()){
            //aquí poner el insertarasignación
            String nombrep = insertaproyecto.getSelectedItem().toString();
            String actualizacion = textoactualizaciones.getText();
            
            if(nombrep.equals("Proyecto") || status.equals("Proceso") || actualizacion.equals("")){
                JOptionPane.showMessageDialog(null,"Llene todos los campos.");
            }else{
                if(status.equals("Finalizado")){
                   JOptionPane.showMessageDialog(null,"Seleccione un estatus válido."); 
                }else{
                tabla.insertarasignacion(nombrep, status, actualizacion);
                tabla.getidasignacion();
                tabla.tablavistaasignaciones(tablaasignacion);
                idasignacion.setText("");
                updateproceso.setSelectedIndex(0);
                insertaproyecto.setSelectedIndex(0);
                textoactualizaciones.setText("");
                insertaproyecto.setEnabled(false);
                textoactualizaciones.setEnabled(false);
                tabla.insertarpersonalasignado(tablaasignados,tabla.setidasignacion());
                tabla.tablaasignados(tablaasignados);
                
                }
            }
        }
  
        
        if(!newcheck.isSelected()){
            //aquí poner el updateasignación
            if(status.equals("Finalizado")){
                   //añadir pantalla de seguro?
                   JOptionPane.showMessageDialog(null,"¿Seguro quiere finalizar la asignación?."); 
                   //añadir updatenormal
                  tabla.updateasignacion(idasignacion.getText(),status);
                  //deshabilitar personalasignado
                }else{
                  int idAsignacion = Integer.parseInt(idasignacion.getText());
                  tabla.updateasignacion(idasignacion.getText(),status);
                  //tabla.updatepersonalasignado(tablaasignados,idasignacion.getText());
                  tabla.insertarpersonalasignado(tablaasignados,idAsignacion);
                  tabla.mostrarpersonal(tablaasignados,idasignacion.getText());
            }
        }
        newcheck.setSelected(false);
        
    }//GEN-LAST:event_guardaMousePressed

    private void tablaasignacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaasignacionMousePressed
        // TODO add your handling code here:
        tabla.mostrarasignaciones(tablaasignacion, idasignacion,updateproceso, insertaproyecto, textoactualizaciones);
        tabla.mostrarpersonal(tablaasignados,idasignacion.getText());
    }//GEN-LAST:event_tablaasignacionMousePressed

    private void limpiafiltroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiafiltroMousePressed
        // TODO add your handling code here:}
        proyectoa.setSelectedIndex(0);
        procesoa.setSelectedIndex(0);
        tabla.tablavistaasignaciones(tablaasignacion);
    }//GEN-LAST:event_limpiafiltroMousePressed

    private void filtraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtraMousePressed
        // TODO add your handling code here:
        String nombreproyecto = proyectoa.getSelectedItem().toString();
        String nombreestatus = procesoa.getSelectedItem().toString();
        if(nombreproyecto.equals("Proyecto")){
            nombreproyecto = null;
        }
        if(nombreestatus.equals("Proceso")){
            nombreestatus = null;
        }
        
        tabla.filtroasignados(tablaasignacion, nombreproyecto, nombreestatus);
        
    }//GEN-LAST:event_filtraMousePressed

    private void guardapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardapMouseClicked
        // TODO add your handling code here:
      //tabla.tablamenup(tablahub);
    }//GEN-LAST:event_guardapMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tablahubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablahubMouseClicked
        // TODO add your handling code here:
      
      try {
            // TODO add your handling code here:
            
            tabla.mostrarproyecto(tablahub,nombrep, pcotiza, streamp, filesize,deadline);
             
        
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MenuProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MenuProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(MenuProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    int filaSeleccionada = tablahub.getSelectedRow();
    int columnaContrato = getColumnaPorNombre("Contrato"); // Ajusta este valor al índice real de la columna "contrato"
    
    if (filaSeleccionada != -1) { // Verificar si se ha seleccionado alguna fila
        Object valorCelda = tablahub.getValueAt(filaSeleccionada, columnaContrato);
        if (valorCelda != null && !valorCelda.toString().isEmpty()) { // Verificar si el valor de la celda no es nulo ni vacío
            nombrecontrato.setText("ArchivoCargado.pdf");
        } else {
            nombrecontrato.setText("sinarchivo.pdf");
        }
    }
    }//GEN-LAST:event_tablahubMouseClicked
    
    //Método para extraer string de la columna del archivo
    private int getColumnaPorNombre(String nombreColumna) {
    for (int i = 0; i < tablahub.getColumnCount(); i++) {
        if (tablahub.getColumnName(i).equals(nombreColumna)) {
            return i;
        }
    }
    return -1; // Retorna -1 si no se encuentra la columna
}
    
    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        //tabla.tablamenup(tablahub);
    }//GEN-LAST:event_jPanel3MouseEntered
    
    



    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borracontrato;
    private javax.swing.JComboBox<String> buscaproyecto;
    private com.toedter.calendar.JDateChooser deadline;
    private javax.swing.JLabel filtra;
    private javax.swing.JLabel filtraproyecto;
    private javax.swing.JButton gcontrato;
    private javax.swing.JButton guarda;
    private javax.swing.JButton guardap;
    private javax.swing.JTextField idasignacion;
    private javax.swing.JComboBox<String> insertaproyecto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel limpiafiltro;
    private javax.swing.JLabel limpiaproyecto;
    private javax.swing.JCheckBox modificar;
    private javax.swing.JCheckBox newcheck;
    private javax.swing.JLabel nombrecontrato;
    private javax.swing.JTextField nombrep;
    private javax.swing.JCheckBox nuevo;
    private javax.swing.JTextField pcotiza;
    private javax.swing.JComboBox<String> procesoa;
    private javax.swing.JComboBox<String> proyectoa;
    private javax.swing.JTable tablaasignacion;
    private javax.swing.JTable tablaasignados;
    private javax.swing.JTable tablahub;
    private javax.swing.JTextPane textoactualizaciones;
    private javax.swing.JLabel titulo;
    private javax.swing.JComboBox<String> updateproceso;
    // End of variables declaration//GEN-END:variables
}
