package gui;


import java.text.SimpleDateFormat;
import java.util.Date;
import logica.TablasDashboard;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Carlos
 */
public class MenuHerramienta extends javax.swing.JFrame {

    /**
     * Creates new form Tool
     */
     int mousex;
     int mousey;
     
     TablasDashboard tablas = new TablasDashboard();
     
    public MenuHerramienta() {
        initComponents();
         
        
        
        tablas.rellenoherramientas(buscaherramienta, combopherramienta, combopersherramienta);
        tablas.tablaherramienta(tablahm);
        
       
        /*
        if(disponibleh.isSelected()){
            tablas
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cerrarherramienta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablahm = new javax.swing.JTable();
        combopherramienta = new javax.swing.JComboBox<>();
        disponibleh = new javax.swing.JRadioButton();
        nodisponibleh = new javax.swing.JRadioButton();
        combopersherramienta = new javax.swing.JComboBox<>();
        muestraherramienta = new javax.swing.JTextField();
        actualizah = new javax.swing.JButton();
        filtraherramienta = new javax.swing.JLabel();
        buscaherramienta = new javax.swing.JComboBox<>();
        limpiaherramienta = new javax.swing.JLabel();
        filtrodisponible = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        cerrarherramienta.setBackground(new java.awt.Color(0, 0, 0));
        cerrarherramienta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cerrarherramienta.setForeground(new java.awt.Color(255, 255, 255));
        cerrarherramienta.setText("X");
        cerrarherramienta.setBorder(null);
        cerrarherramienta.setBorderPainted(false);
        cerrarherramienta.setContentAreaFilled(false);
        cerrarherramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarherramienta.setFocusPainted(false);
        cerrarherramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarherramientaMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Herramientas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cerrarherramienta, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        tablahm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Herramienta", "Proyecto", "Personal", "Estatus", "Última vez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablahm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablahmMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablahm);

        combopherramienta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto" }));
        combopherramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopherramientaActionPerformed(evt);
            }
        });

        disponibleh.setBackground(new java.awt.Color(255, 255, 255));
        disponibleh.setText("Disponible");
        disponibleh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disponibleh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                disponiblehMousePressed(evt);
            }
        });
        disponibleh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponiblehActionPerformed(evt);
            }
        });

        nodisponibleh.setBackground(new java.awt.Color(255, 255, 255));
        nodisponibleh.setText("No disponible");
        nodisponibleh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nodisponiblehMousePressed(evt);
            }
        });

        combopersherramienta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal" }));

        muestraherramienta.setEditable(false);
        muestraherramienta.setBackground(new java.awt.Color(255, 255, 255));

        actualizah.setText("Actualizar");
        actualizah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actualizahMousePressed(evt);
            }
        });

        filtraherramienta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/icone-de-filtre-noir (1).png"))); // NOI18N
        filtraherramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtraherramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                filtraherramientaMousePressed(evt);
            }
        });

        buscaherramienta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Herramienta" }));
        buscaherramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaherramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscaherramientaMousePressed(evt);
            }
        });
        buscaherramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaherramientaActionPerformed(evt);
            }
        });

        limpiaherramienta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/botecito (1).png"))); // NOI18N
        limpiaherramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiaherramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiaherramientaMousePressed(evt);
            }
        });

        filtrodisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponibilidad", "Disponible", "No" }));
        filtrodisponible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtrodisponible.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(filtraherramienta)
                        .addGap(12, 12, 12)
                        .addComponent(filtrodisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(buscaherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limpiaherramienta)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disponibleh)
                    .addComponent(nodisponibleh)
                    .addComponent(actualizah)
                    .addComponent(muestraherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(combopherramienta, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(combopersherramienta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(muestraherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combopherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combopersherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disponibleh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nodisponibleh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizah)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(filtraherramienta)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(filtrodisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buscaherramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(limpiaherramienta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarherramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarherramientaMousePressed
        // TODO add your handling code here:
        Home herramienta = new Home();
        herramienta.refreshherramienta();
        this.dispose();

    }//GEN-LAST:event_cerrarherramientaMousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
       
        this.setLocation(x - mousex,y - mousey);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void combopherramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopherramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combopherramientaActionPerformed

    private void disponiblehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponiblehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disponiblehActionPerformed

    private void filtraherramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtraherramientaMousePressed
        // TODO add your handling code here:
        String nombrep;
        String estatus;
        TablasDashboard tabladashboard = new TablasDashboard();

        nombrep = (String) buscaherramienta.getSelectedItem();
        estatus = (String) filtrodisponible.getSelectedItem();
        if(nombrep.equals("Herramienta")){
            nombrep = null;
        }
        
        if(estatus.equals("Disponibilidad")){
            estatus = null;
        }

        
        tabladashboard.filtroherramienta(tablahm, estatus, nombrep);
    }//GEN-LAST:event_filtraherramientaMousePressed

    private void buscaherramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaherramientaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaherramientaMousePressed

    private void buscaherramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaherramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaherramientaActionPerformed

    private void limpiaherramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiaherramientaMousePressed
        // TODO add your handling code here:
        buscaherramienta.setSelectedIndex(0);
        filtrodisponible.setSelectedIndex(0);
    }//GEN-LAST:event_limpiaherramientaMousePressed

    private void tablahmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablahmMousePressed
        // TODO add your handling code here:
      
     
      tablas.mostrarherramienta(tablahm ,muestraherramienta,combopherramienta,combopersherramienta,disponibleh,nodisponibleh);
      
      
    }//GEN-LAST:event_tablahmMousePressed

    private void disponiblehMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disponiblehMousePressed
        // TODO add your handling code here:
       
            nodisponibleh.setSelected(false);
           
        
    }//GEN-LAST:event_disponiblehMousePressed

    private void nodisponiblehMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nodisponiblehMousePressed
        // TODO add your handling code here:
          
          disponibleh.setSelected(false);
          
    }//GEN-LAST:event_nodisponiblehMousePressed

    private void actualizahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizahMousePressed
        // TODO add your handling code here:
        //Home vistahome = new Home();
        //Home herramienta = new Home();
        tablas.updateherramienta(tablahm ,muestraherramienta,combopherramienta,combopersherramienta,disponibleh,nodisponibleh);
        tablas.tablaherramienta(tablahm);
        //Actualizar en dashboard home
        //herramienta.refreshherramienta();
    }//GEN-LAST:event_actualizahMousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizah;
    private javax.swing.JComboBox<String> buscaherramienta;
    private javax.swing.JButton cerrarherramienta;
    private javax.swing.JComboBox<String> combopersherramienta;
    private javax.swing.JComboBox<String> combopherramienta;
    private javax.swing.JRadioButton disponibleh;
    private javax.swing.JLabel filtraherramienta;
    private javax.swing.JComboBox<String> filtrodisponible;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel limpiaherramienta;
    private javax.swing.JTextField muestraherramienta;
    private javax.swing.JRadioButton nodisponibleh;
    private javax.swing.JTable tablahm;
    // End of variables declaration//GEN-END:variables
}
