/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import logica.TablasVehiculos;

/**
 *
 * @author Carlos
 */
public class MenuVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form MenuVehiculo
     */
    int mousex;
    int mousey;
    String fecha;
    TablasVehiculos tablas = new TablasVehiculos();
    ProximoPago proximo = new ProximoPago();
    public MenuVehiculo() {
        initComponents();
        
        tablas.rellenovehiculos(filtrovehiculo);
        tablas.rellenovehiculos2(actualizapersonal, proyectov);
        tablas.tablamenuv(tablamenuv);
        
        habilitac.setSelected(false);
        
       if( !habilitao.isSelected()){
      
           montoc.setEnabled(false);
           montoo.setEnabled(false);
           mantenimiento.setEnabled(false);
           mantenimiento.setSelected(false);
           consumibles.setEnabled(false);
           consumibles.setSelected(false);
           refacciones.setEnabled(false);
           refacciones.setSelected(false);
           seguro.setEnabled(false);
           seguro.setSelected(false);
           verificacion.setEnabled(false);
           verificacion.setSelected(false);
           tenencia.setEnabled(false);
           tenencia.setSelected(false);
        }
             
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        botonfiltro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablamenuv = new javax.swing.JTable();
        limpiavehiculo = new javax.swing.JLabel();
        filtrovehiculo = new javax.swing.JComboBox<>();
        filtrodisponible = new javax.swing.JComboBox<>();
        nombrev = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        montoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        montoo = new javax.swing.JTextField();
        habilitac = new javax.swing.JRadioButton();
        habilitao = new javax.swing.JRadioButton();
        mantenimiento = new javax.swing.JRadioButton();
        consumibles = new javax.swing.JRadioButton();
        seguro = new javax.swing.JRadioButton();
        refacciones = new javax.swing.JRadioButton();
        tenencia = new javax.swing.JRadioButton();
        verificacion = new javax.swing.JRadioButton();
        actualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nodisponible = new javax.swing.JRadioButton();
        disponible = new javax.swing.JRadioButton();
        actualizapersonal = new javax.swing.JComboBox<>();
        proyectov = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vehículos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );

        botonfiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/icone-de-filtre-noir (1).png"))); // NOI18N
        botonfiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonfiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonfiltroMousePressed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPane1MousePressed(evt);
            }
        });

        tablamenuv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehículo", "Estatus", "Proyecto", "Personal", "Gastos del mes", "Próximo pago", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablamenuv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablamenuvMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablamenuv);
        if (tablamenuv.getColumnModel().getColumnCount() > 0) {
            tablamenuv.getColumnModel().getColumn(0).setResizable(false);
            tablamenuv.getColumnModel().getColumn(1).setResizable(false);
            tablamenuv.getColumnModel().getColumn(2).setResizable(false);
            tablamenuv.getColumnModel().getColumn(3).setResizable(false);
            tablamenuv.getColumnModel().getColumn(4).setResizable(false);
            tablamenuv.getColumnModel().getColumn(5).setResizable(false);
            tablamenuv.getColumnModel().getColumn(6).setResizable(false);
        }

        limpiavehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/botecito (1).png"))); // NOI18N
        limpiavehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiavehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiavehiculoMousePressed(evt);
            }
        });

        filtrovehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehículo" }));
        filtrovehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtrovehiculo.setFocusable(false);
        filtrovehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrovehiculoActionPerformed(evt);
            }
        });

        filtrodisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponibilidad", "Disponible", "No" }));
        filtrodisponible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtrodisponible.setFocusable(false);

        nombrev.setBackground(new java.awt.Color(204, 204, 204));
        nombrev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nombrev.setEnabled(false);
        nombrev.setFocusable(false);

        jLabel2.setText("Combustible:");

        montoc.setDragEnabled(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Vehículo:");

        jLabel1.setText("Otros gastos");

        jLabel4.setText("Monto:");

        habilitac.setContentAreaFilled(false);
        habilitac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habilitac.setFocusPainted(false);
        habilitac.setFocusable(false);
        habilitac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                habilitacMousePressed(evt);
            }
        });
        habilitac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitacActionPerformed(evt);
            }
        });

        habilitao.setContentAreaFilled(false);
        habilitao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habilitao.setFocusPainted(false);
        habilitao.setFocusable(false);
        habilitao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habilitaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                habilitaoMousePressed(evt);
            }
        });
        habilitao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitaoActionPerformed(evt);
            }
        });

        mantenimiento.setText("Mantenimiento");
        mantenimiento.setContentAreaFilled(false);
        mantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mantenimiento.setFocusPainted(false);
        mantenimiento.setFocusable(false);
        mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mantenimientoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mantenimientoMousePressed(evt);
            }
        });

        consumibles.setText("Consumibles");
        consumibles.setContentAreaFilled(false);
        consumibles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consumibles.setFocusPainted(false);
        consumibles.setFocusable(false);
        consumibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consumiblesMousePressed(evt);
            }
        });
        consumibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumiblesActionPerformed(evt);
            }
        });

        seguro.setText("Seguro");
        seguro.setContentAreaFilled(false);
        seguro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seguro.setFocusPainted(false);
        seguro.setFocusable(false);
        seguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seguroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seguroMousePressed(evt);
            }
        });

        refacciones.setText("Refacciones");
        refacciones.setContentAreaFilled(false);
        refacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refacciones.setFocusPainted(false);
        refacciones.setFocusable(false);
        refacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refaccionesMousePressed(evt);
            }
        });

        tenencia.setText("Tenencia");
        tenencia.setContentAreaFilled(false);
        tenencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tenencia.setFocusPainted(false);
        tenencia.setFocusable(false);
        tenencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenenciaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tenenciaMousePressed(evt);
            }
        });

        verificacion.setText("Verificación");
        verificacion.setContentAreaFilled(false);
        verificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verificacion.setFocusPainted(false);
        verificacion.setFocusable(false);
        verificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verificacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verificacionMousePressed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizar.setFocusable(false);
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actualizarMousePressed(evt);
            }
        });

        jLabel5.setText("Disponibilidad:");

        nodisponible.setText("No disponible");
        nodisponible.setContentAreaFilled(false);
        nodisponible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nodisponible.setFocusPainted(false);
        nodisponible.setFocusable(false);
        nodisponible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nodisponibleMousePressed(evt);
            }
        });
        nodisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodisponibleActionPerformed(evt);
            }
        });

        disponible.setText("Disponible");
        disponible.setContentAreaFilled(false);
        disponible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disponible.setFocusable(false);
        disponible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                disponibleMousePressed(evt);
            }
        });

        actualizapersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal" }));
        actualizapersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        proyectov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto" }));
        proyectov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botonfiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filtrovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filtrodisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limpiavehiculo)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(habilitac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(montoo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(montoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(nombrev, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consumibles)
                                    .addComponent(mantenimiento)
                                    .addComponent(refacciones)
                                    .addComponent(seguro)
                                    .addComponent(verificacion)
                                    .addComponent(tenencia))))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(actualizapersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proyectov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(habilitao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(disponible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nodisponible)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(actualizar)
                                .addGap(121, 121, 121))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrev, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(montoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(habilitac))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(habilitao)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(montoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(mantenimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumibles)
                        .addGap(5, 5, 5)
                        .addComponent(refacciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seguro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenencia)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(actualizapersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proyectov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nodisponible)
                            .addComponent(disponible))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizar)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonfiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(filtrovehiculo)
                                    .addComponent(filtrodisponible)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(limpiavehiculo)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(23, 23, 23))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiavehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiavehiculoMousePressed
        // TODO add your handling code here:
        filtrovehiculo.setSelectedIndex(0);
        filtrodisponible.setSelectedIndex(0);
        
    }//GEN-LAST:event_limpiavehiculoMousePressed

    private void habilitacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habilitacActionPerformed

    private void habilitaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habilitaoActionPerformed

    private void consumiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumiblesActionPerformed

    private void nodisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodisponibleActionPerformed

    private void filtrovehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrovehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrovehiculoActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
       
        this.setLocation(x - mousex,y - mousey);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void habilitacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitacMousePressed
        // TODO add your handling code here:
        if(habilitac.isSelected()){
            montoc.setEnabled(false);
        } else {
            // Si habilitac no está seleccionado, habilita montoc
            montoc.setEnabled(true);
        } 
    }//GEN-LAST:event_habilitacMousePressed

    private void habilitaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitaoMousePressed
        // TODO add your handling code here:
        if(habilitao.isSelected()){
             montoo.setEnabled(false);
             mantenimiento.setEnabled(false);
             consumibles.setEnabled(false);
             refacciones.setEnabled(false);
             seguro.setEnabled(false);
             verificacion.setEnabled(false);
             tenencia.setEnabled(false);

        }
            if(!habilitao.isSelected()){
            montoo.setEnabled(true);
            mantenimiento.setEnabled(true);
            consumibles.setEnabled(true);
            refacciones.setEnabled(true);
            seguro.setEnabled(true);
            verificacion.setEnabled(true);
            tenencia.setEnabled(true);
            }
            
            if( !habilitao.isSelected()){
 
           mantenimiento.setSelected(false);
           consumibles.setSelected(false);
           refacciones.setSelected(false);
           seguro.setSelected(false);
           verificacion.setSelected(false);
           tenencia.setSelected(false);
        }
            
           
    }//GEN-LAST:event_habilitaoMousePressed

    private void mantenimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mantenimientoMousePressed
        // TODO add your handling code here:
      // if(mantenimiento.isSelected()){
                consumibles.setSelected(false);
                refacciones.setSelected(false);
                seguro.setSelected(false);
                verificacion.setSelected(false);
                tenencia.setSelected(false);   
         //  }
       if( !habilitao.isSelected()){
      
           montoc.setEnabled(false);
           montoo.setEnabled(false);
           mantenimiento.setEnabled(false);
           mantenimiento.setSelected(false);
           consumibles.setEnabled(false);
           consumibles.setSelected(false);
           refacciones.setEnabled(false);
           refacciones.setSelected(false);
           seguro.setEnabled(false);
           seguro.setSelected(false);
           verificacion.setEnabled(false);
           verificacion.setSelected(false);
           tenencia.setEnabled(false);
           tenencia.setSelected(false);
        }
             
    }//GEN-LAST:event_mantenimientoMousePressed

    private void consumiblesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consumiblesMousePressed
        // TODO add your handling code here:
        //if(consumibles.isSelected()){
                mantenimiento.setSelected(false);
                refacciones.setSelected(false);
                seguro.setSelected(false);
                verificacion.setSelected(false);
                tenencia.setSelected(false);
                
          // }
          if( !habilitao.isSelected()){
      
           montoc.setEnabled(false);
           montoo.setEnabled(false);
           mantenimiento.setEnabled(false);
           mantenimiento.setSelected(false);
           consumibles.setEnabled(false);
           consumibles.setSelected(false);
           refacciones.setEnabled(false);
           refacciones.setSelected(false);
           seguro.setEnabled(false);
           seguro.setSelected(false);
           verificacion.setEnabled(false);
           verificacion.setSelected(false);
           tenencia.setEnabled(false);
           tenencia.setSelected(false);
        }
             
    }//GEN-LAST:event_consumiblesMousePressed

    private void refaccionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refaccionesMousePressed
        // TODO add your handling code here:
       //if(refacciones.isSelected()){
                mantenimiento.setSelected(false);
                consumibles.setSelected(false);
                seguro.setSelected(false);
                verificacion.setSelected(false);
                tenencia.setSelected(false);
         //  }
         if( !habilitao.isSelected()){
      
           montoc.setEnabled(false);
           montoo.setEnabled(false);
           mantenimiento.setEnabled(false);
           mantenimiento.setSelected(false);
           consumibles.setEnabled(false);
           consumibles.setSelected(false);
           refacciones.setEnabled(false);
           refacciones.setSelected(false);
           seguro.setEnabled(false);
           seguro.setSelected(false);
           verificacion.setEnabled(false);
           verificacion.setSelected(false);
           tenencia.setEnabled(false);
           tenencia.setSelected(false);
        }
             
    }//GEN-LAST:event_refaccionesMousePressed

    private void seguroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seguroMousePressed
        // TODO add your handling code here:
        //if(seguro.isSelected()){
                mantenimiento.setSelected(false);
                consumibles.setSelected(false);
                refacciones.setSelected(false);
                verificacion.setSelected(false);
                tenencia.setSelected(false);
         //  }
    }//GEN-LAST:event_seguroMousePressed

    private void verificacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verificacionMousePressed
        // TODO add your handling code here:
        // if(verificacion.isSelected()){
                mantenimiento.setSelected(false);
                consumibles.setSelected(false);
                refacciones.setSelected(false);
                seguro.setSelected(false);
                tenencia.setSelected(false);
         //  }
          if( !habilitao.isSelected()){
      
           montoc.setEnabled(false);
           montoo.setEnabled(false);
           mantenimiento.setEnabled(false);
           mantenimiento.setSelected(false);
           consumibles.setEnabled(false);
           consumibles.setSelected(false);
           refacciones.setEnabled(false);
           refacciones.setSelected(false);
           seguro.setEnabled(false);
           seguro.setSelected(false);
           verificacion.setEnabled(false);
           verificacion.setSelected(false);
           tenencia.setEnabled(false);
           tenencia.setSelected(false);
        }
             
    }//GEN-LAST:event_verificacionMousePressed

    private void tenenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenenciaMousePressed
        // TODO add your handling code here:
       // if(tenencia.isSelected()){
                mantenimiento.setSelected(false);
                consumibles.setSelected(false);
                refacciones.setSelected(false);
                seguro.setSelected(false);
                verificacion.setSelected(false);
          // }
         if( !habilitao.isSelected()){
      
           montoc.setEnabled(false);
           montoo.setEnabled(false);
           mantenimiento.setEnabled(false);
           mantenimiento.setSelected(false);
           consumibles.setEnabled(false);
           consumibles.setSelected(false);
           refacciones.setEnabled(false);
           refacciones.setSelected(false);
           seguro.setEnabled(false);
           seguro.setSelected(false);
           verificacion.setEnabled(false);
           verificacion.setSelected(false);
           tenencia.setEnabled(false);
           tenencia.setSelected(false);
        }
             
            
    }//GEN-LAST:event_tenenciaMousePressed

    private void disponibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disponibleMousePressed
        // TODO add your handling code here:
        nodisponible.setSelected(false);
    }//GEN-LAST:event_disponibleMousePressed

    private void nodisponibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nodisponibleMousePressed
        // TODO add your handling code here:
        disponible.setSelected(false);
    }//GEN-LAST:event_nodisponibleMousePressed

    private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MousePressed

    private void tablamenuvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamenuvMousePressed
        // TODO add your handling code here:
        tablas.mostrarvehiculo(tablamenuv, nombrev, proyectov, actualizapersonal, disponible, nodisponible);
    }//GEN-LAST:event_tablamenuvMousePressed

    private void actualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMousePressed
        // TODO add your handling code here:
        String montocombustible;
        String nombrevehiculo;
        String montogastos = null;
       
        tablas.updatevehiculo(tablamenuv, nombrev, proyectov, actualizapersonal, disponible, nodisponible);
        tablas.tablamenuv(tablamenuv);
        
        if(montoc.isEnabled()){
          nombrevehiculo = nombrev.getText();
          montocombustible = montoc.getText();
          
          tablas.insertacombustible(nombrevehiculo, montocombustible);
            
        }
       /* if(montoo.isEnabled()){
          montocombustible = montoo.getText();
        }
        */
        if(mantenimiento.isSelected()){
         
           fecha = proximo.setfecha();
           tablas.insertamantenimiento(nombrev.getText(), fecha, montoo.getText());
          
        }   
        
        if(consumibles.isSelected()){
            tablas.insertarconsumibles(nombrev.getText(),montoo.getText());
        }
        
        if(refacciones.isSelected()){
            tablas.insertarrefacciones(nombrev.getText(),montoo.getText());
        }
        
        if(seguro.isSelected()){
           fecha = proximo.setfecha();
           tablas.insertarseguro(nombrev.getText(), fecha, montoo.getText());  
        }
        
        if(verificacion.isSelected()){
           fecha = proximo.setfecha();
           tablas.insertarverificacion(nombrev.getText(), fecha, montoo.getText());  
        }
        
        if(tenencia.isSelected()){ 
           fecha = proximo.setfecha();
           tablas.insertartenencias(nombrev.getText(), fecha, montoo.getText());  
        }
        
       //Resetear todos los botones cuando se inserte un nuevo gasto
       habilitac.setSelected(false);
       habilitao.setSelected(false);
       montoc.setEnabled(false);
       montoo.setEnabled(false);
       mantenimiento.setEnabled(false);
       mantenimiento.setSelected(false);
       consumibles.setEnabled(false);
       consumibles.setSelected(false);
       refacciones.setEnabled(false);
       refacciones.setSelected(false);
       seguro.setEnabled(false);
       seguro.setSelected(false);
       verificacion.setEnabled(false);
       verificacion.setSelected(false);
       tenencia.setEnabled(false);
       tenencia.setSelected(false);
       actualizapersonal.setSelectedIndex(0);
       proyectov.setSelectedIndex(0); 
       disponible.setSelected(false);
       nodisponible.setSelected(false);
       nombrev.setText("");
       montoc.setText("");
       montoo.setText("");
        
    }//GEN-LAST:event_actualizarMousePressed

    private void mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mantenimientoMouseClicked
        // TODO add your handling code here:
        if(mantenimiento.isSelected()){
                 
                proximo.setVisible(true);
                proximo.setLocationRelativeTo(null);
                // hacer get set desde ventana temporal  
           }   
    }//GEN-LAST:event_mantenimientoMouseClicked

    private void seguroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seguroMouseClicked
        // TODO add your handling code here:
        if(seguro.isSelected()){
            proximo.setVisible(true);
            proximo.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_seguroMouseClicked

    private void verificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verificacionMouseClicked
        // TODO add your handling code here:
        if(verificacion.isSelected()){
            proximo.setVisible(true);
            proximo.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_verificacionMouseClicked

    private void tenenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenenciaMouseClicked
        // TODO add your handling code here:
        if(tenencia.isSelected()){
            proximo.setVisible(true);
            proximo.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_tenenciaMouseClicked

    private void botonfiltroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonfiltroMousePressed
        // TODO add your handling code here:
        String namev = filtrovehiculo.getSelectedItem().toString();
        String availablev = filtrodisponible.getSelectedItem().toString();
        
        if(namev.equals("Vehículo")){
            namev = null;
        }
        
        if(availablev.equals("Disponibilidad")){
            availablev = null;
        }
        
        
        tablas.filtrarvehiculo(tablamenuv,namev,availablev);
    }//GEN-LAST:event_botonfiltroMousePressed

    private void habilitaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitaoMouseClicked
        // TODO add your handling code here:
        if( !habilitao.isSelected()){
      
           montoc.setEnabled(false);
           montoo.setEnabled(false);
           mantenimiento.setEnabled(false);
           mantenimiento.setSelected(false);
           consumibles.setEnabled(false);
           consumibles.setSelected(false);
           refacciones.setEnabled(false);
           refacciones.setSelected(false);
           seguro.setEnabled(false);
           seguro.setSelected(false);
           verificacion.setEnabled(false);
           verificacion.setSelected(false);
           tenencia.setEnabled(false);
           tenencia.setSelected(false);
        }
             
    }//GEN-LAST:event_habilitaoMouseClicked


 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actualizapersonal;
    private javax.swing.JButton actualizar;
    private javax.swing.JLabel botonfiltro;
    private javax.swing.JRadioButton consumibles;
    private javax.swing.JRadioButton disponible;
    private javax.swing.JComboBox<String> filtrodisponible;
    private javax.swing.JComboBox<String> filtrovehiculo;
    private javax.swing.JRadioButton habilitac;
    private javax.swing.JRadioButton habilitao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel limpiavehiculo;
    private javax.swing.JRadioButton mantenimiento;
    private javax.swing.JTextField montoc;
    private javax.swing.JTextField montoo;
    private javax.swing.JRadioButton nodisponible;
    private javax.swing.JLabel nombrev;
    private javax.swing.JComboBox<String> proyectov;
    private javax.swing.JRadioButton refacciones;
    private javax.swing.JRadioButton seguro;
    private javax.swing.JTable tablamenuv;
    private javax.swing.JRadioButton tenencia;
    private javax.swing.JRadioButton verificacion;
    // End of variables declaration//GEN-END:variables
}
