/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.awt.event.KeyListener;
import persistance.sqlconectar;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import logica.Validar;
/**
 *
 * @author Carlos
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        ImageIcon icono = new ImageIcon(getClass().getResource("/fotos/images/Orsalogo.png")); // Reemplaza "/ruta/a/tu/logo.png" con la ruta real de tu logo
        setIconImage(icono.getImage());
    }
    int mousex, mousey;
    //sqlconectar connect = new sqlconectar();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        background1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inusername = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        valida = new javax.swing.JButton();
        inpassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/Orsalogo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 110, 180, 120);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("INGENIERÍA ORSA SA. DE CV.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 240, 370, 70);

        salir.setBackground(new java.awt.Color(0, 153, 0));
        salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salir.setText("X");
        salir.setBorder(null);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });
        jPanel1.add(salir);
        salir.setBounds(340, 0, 50, 40);

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 480, 440));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Iniciar sesión");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 93, 0, 70));

        background1.setBackground(new java.awt.Color(255, 255, 255));
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/images/Orsalogo.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 110, 180, 120);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("INGENIERÍA ORSA SA. DE CV.");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 240, 370, 70);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("X");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(360, 0, 20, 30);

        background1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 690, 440));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Iniciar sesión");
        background1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        inusername.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        inusername.setForeground(new java.awt.Color(204, 204, 204));
        inusername.setText("Ingrese su usuario");
        inusername.setToolTipText("");
        inusername.setBorder(null);
        inusername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inusernameMousePressed(evt);
            }
        });
        inusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inusernameActionPerformed(evt);
            }
        });
        background1.add(inusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 370, -1));
        background1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 93, 0, 70));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        background1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 380, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Usuario:");
        background1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Contraseña:");
        background1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 390, 10));

        valida.setBackground(new java.awt.Color(153, 153, 153));
        valida.setText("Inicio");
        valida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        valida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                validaMousePressed(evt);
            }
        });
        valida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validaKeyReleased(evt);
            }
        });
        background1.add(valida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        inpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inpassword.setForeground(new java.awt.Color(204, 204, 204));
        inpassword.setText("******");
        inpassword.setBorder(null);
        inpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inpasswordMousePressed(evt);
            }
        });
        background1.add(inpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 390, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        background1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        background.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        jDesktopPane1.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inusernameActionPerformed

    private void inusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inusernameMousePressed
       if(inusername.getText().equals("Ingrese su usuario")){
       inusername.setText("");
       inusername.setForeground(Color.black);
       }
       if(String.valueOf(inpassword.getPassword()).isEmpty()){
       inpassword.setText("******");
       inpassword.setForeground(Color.gray);
       }
    }//GEN-LAST:event_inusernameMousePressed

    private void inpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpasswordMousePressed
      
       if(String.valueOf(inpassword.getPassword()).equals("******")){
       inpassword.setText("");
       inpassword.setForeground(Color.black);
       }
       if(inusername.getText().isEmpty()){
       inusername.setText("Ingrese su usuario");
       inusername.setForeground(Color.gray);
       }
    }//GEN-LAST:event_inpasswordMousePressed

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        System.exit(0);
    }//GEN-LAST:event_salirMousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex,y - mousey);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setBackground(Color.red);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_salirMouseExited

    private void validaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validaMousePressed
        //aquí se va a validar la contraseña y el usuario
            logica.Validar objetovalidar = new logica.Validar();
            String username = inusername.getText();
            String password = String.valueOf(inpassword.getPassword());
        
           objetovalidar.validaruser(username,password);
           
            switch (objetovalidar.confirmar()){
             case 0:
             username = inusername.getText();
             password = String.valueOf(inpassword.getPassword());
     
             break;
             case 1:
                 this.dispose();
                 break;
  
            }
        
        
                

    }//GEN-LAST:event_validaMousePressed

    private void validaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_validaKeyReleased

    private void validaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaKeyPressed
        // TODO add your handling code here:
       // KeyListener keyCode = new KeyListener();
     
        logica.Validar objetovalidar = new logica.Validar();
            String username = inusername.getText();
            String password = String.valueOf(inpassword.getPassword());
        
           objetovalidar.validaruser(username,password);
           
            switch (objetovalidar.confirmar()){
             case 0:
             username = inusername.getText();
             password = String.valueOf(inpassword.getPassword());
     
             break;
             case 1:
                 this.dispose();
                 break;
  
            }
    }//GEN-LAST:event_validaKeyPressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JPasswordField inpassword;
    private javax.swing.JTextField inusername;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton salir;
    private javax.swing.JButton valida;
    // End of variables declaration//GEN-END:variables
}
